version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  py36:
    docker:
      - image: cimg/python:3.6
    steps:
      - checkout
      - run:
          command: pip install tox
      - run:
          command: tox -e py36

  py37:
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - run:
          command: pip install tox
      - run:
          command: tox -e py37

  py38:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          command: pip install tox
      - run:
          command: tox -e py38

  py39:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          command: pip install tox
      - run:
          command: tox -e py39,lint

  py310:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          command: pip install tox
      - run:
          command: tox -e py310


workflows:
  main:
    jobs:
      - py36
      - py37
      - py38
      - py39
      - py310
